// Национальность (как отдаёт провайдер, англ. прилагательное) -> {RU, ISO2 для флага}.
export const NATIONALITY: Record<string, { ru: string; code: string }> = {
  Dutch: { ru: "Нидерланды", code: "nl" },
  British: { ru: "Великобритания", code: "gb" },
  Monegasque: { ru: "Монако", code: "mc" },
  Australian: { ru: "Австралия", code: "au" },
  Spanish: { ru: "Испания", code: "es" },
  Italian: { ru: "Италия", code: "it" },
  Mexican: { ru: "Мексика", code: "mx" },
  French: { ru: "Франция", code: "fr" },
  German: { ru: "Германия", code: "de" },
  Finnish: { ru: "Финляндия", code: "fi" },
  Canadian: { ru: "Канада", code: "ca" },
  Thai: { ru: "Таиланд", code: "th" },
  Japanese: { ru: "Япония", code: "jp" },
  Danish: { ru: "Дания", code: "dk" },
  Chinese: { ru: "Китай", code: "cn" },
  American: { ru: "США", code: "us" },
  Brazilian: { ru: "Бразилия", code: "br" },
  Argentine: { ru: "Аргентина", code: "ar" },
  Argentinian: { ru: "Аргентина", code: "ar" },
  "New Zealander": { ru: "Новая Зеландия", code: "nz" },
  Austrian: { ru: "Австрия", code: "at" },
  Swiss: { ru: "Швейцария", code: "ch" },
  Belgian: { ru: "Бельгия", code: "be" },
};
