# Автогенерировано из bacinger/f1-circuits (MIT): длина(м), год открытия, первый Гран-при, город, англ. название.

CIRCUIT_FACTS: dict[str, dict] = {
    'albert_park': {"name_en": 'Albert Park Circuit', "length_m": 5278, "opened": 1953, "first_gp": 1996, "locality": 'Melbourne'},
    'bahrain': {"name_en": 'Bahrain International Circuit', "length_m": 5412, "opened": 2002, "first_gp": 2004, "locality": 'Sakhir'},
    'shanghai': {"name_en": 'Shanghai International Circuit', "length_m": 5451, "opened": 2004, "first_gp": 2004, "locality": 'Shanghai'},
    'catalunya': {"name_en": 'Circuit de Barcelona-Catalunya', "length_m": 4655, "opened": 1991, "first_gp": 1991, "locality": 'Barcelona'},
    'monaco': {"name_en": 'Circuit de Monaco', "length_m": 3337, "opened": 1929, "first_gp": 1929, "locality": 'Monaco'},
    'villeneuve': {"name_en": 'Circuit Gilles-Villeneuve', "length_m": 4361, "opened": 1978, "first_gp": 1978, "locality": 'Montreal'},
    'red_bull_ring': {"name_en": 'Red Bull Ring', "length_m": 4318, "opened": 1969, "first_gp": 1970, "locality": 'Spielberg'},
    'silverstone': {"name_en": 'Silverstone Circuit', "length_m": 5891, "opened": 1948, "first_gp": 1950, "locality": 'Silverstone'},
    'hungaroring': {"name_en": 'Hungaroring', "length_m": 4381, "opened": 1986, "first_gp": 1986, "locality": 'Budapest'},
    'spa': {"name_en": 'Circuit de Spa-Francorchamps', "length_m": 7004, "opened": 1925, "first_gp": 1950, "locality": 'Spa Francorchamps'},
    'monza': {"name_en": 'Autodromo Nazionale Monza', "length_m": 5793, "opened": 1922, "first_gp": 1950, "locality": 'Monza'},
    'marina_bay': {"name_en": 'Marina Bay Street Circuit', "length_m": 4928, "opened": 2008, "first_gp": 2008, "locality": 'Singapore'},
    'suzuka': {"name_en": 'Suzuka International Racing Course', "length_m": 5807, "opened": 1962, "first_gp": 1987, "locality": 'Suzuka'},
    'americas': {"name_en": 'Circuit of the Americas', "length_m": 5514, "opened": 2012, "first_gp": 2012, "locality": 'Austin'},
    'rodriguez': {"name_en": 'Autódromo Hermanos Rodríguez', "length_m": 4304, "opened": 1962, "first_gp": 1963, "locality": 'Mexico City'},
    'interlagos': {"name_en": 'Autódromo José Carlos Pace - Interlagos', "length_m": 4309, "opened": 1940, "first_gp": 1973, "locality": 'Sao Paulo'},
    'yas_marina': {"name_en": 'Yas Marina Circuit', "length_m": 5281, "opened": 2009, "first_gp": 2009, "locality": 'Yas Marina'},
    'imola': {"name_en": 'Autodromo Enzo e Dino Ferrari', "length_m": 4909, "opened": 1953, "first_gp": 1980, "locality": 'Imola'},
    'portimao': {"name_en": 'Autódromo Internacional do Algarve', "length_m": 4653, "opened": 2008, "first_gp": 2020, "locality": 'Portimão'},
    'mugello': {"name_en": 'Autodromo Internazionale del Mugello', "length_m": 5245, "opened": 1914, "first_gp": 2020, "locality": 'Scarperia e San Piero'},
    'sepang': {"name_en": 'Sepang International Circuit', "length_m": 5543, "opened": 1999, "first_gp": 1999, "locality": 'Sepang'},
    'zandvoort': {"name_en": 'Circuit Zandvoort', "length_m": 4259, "opened": 1948, "first_gp": 1952, "locality": 'Zandvoort'},
    'jeddah': {"name_en": 'Jeddah Corniche Circuit', "length_m": 6175, "opened": 2021, "first_gp": 2021, "locality": 'Jeddah'},
    'miami': {"name_en": 'Miami International Autodrome', "length_m": 5412, "opened": 2022, "first_gp": 2022, "locality": 'Miami'},
    'losail': {"name_en": 'Losail International Circuit', "length_m": 5380, "opened": 2004, "first_gp": 2021, "locality": 'Lusail'},
    'madring': {"name_en": 'Circuito de Madring', "length_m": 5474, "opened": 2026, "first_gp": 2026, "locality": 'Madrid'},
    'madrid': {"name_en": 'Circuito de Madring', "length_m": 5474, "opened": 2026, "first_gp": 2026, "locality": 'Madrid'},
    'baku': {"name_en": 'Baku City Circuit', "length_m": 6003, "opened": 2016, "first_gp": 2016, "locality": 'Baku'},
    'vegas': {"name_en": 'Las Vegas Street Circuit', "length_m": 6201, "opened": 2023, "first_gp": 2023, "locality": 'Las Vegas'},
    'las_vegas': {"name_en": 'Las Vegas Street Circuit', "length_m": 6201, "opened": 2023, "first_gp": 2023, "locality": 'Las Vegas'},
}
